#!/usr/bin/env python3
#
# Author: Vláďa Janeček <vlada@janecek.cloud>
#
# Decodes a non-interlaced 8-bit RGBA PNG (no PIL needed at build time)
# and emits it as a C header with raw RGBA bytes.
import struct
import sys
import zlib


def decode(path):
    data = open(path, "rb").read()
    assert data[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG"
    pos, idat, w, h = 8, b"", 0, 0
    while pos < len(data):
        ln, typ = struct.unpack(">I4s", data[pos:pos + 8])
        chunk = data[pos + 8:pos + 8 + ln]
        if typ == b"IHDR":
            w, h, depth, ctype = struct.unpack(">IIBB", chunk[:10])
            assert depth == 8 and ctype == 6, "need 8-bit RGBA"
        elif typ == b"IDAT":
            idat += chunk
        pos += 12 + ln
    raw = zlib.decompress(idat)
    stride = w * 4
    out = bytearray(h * stride)
    prev = bytearray(stride)
    p = 0
    for y in range(h):
        f = raw[p]
        line = bytearray(raw[p + 1:p + 1 + stride])
        p += 1 + stride
        if f == 1:      # Sub
            for i in range(4, stride):
                line[i] = (line[i] + line[i - 4]) & 0xff
        elif f == 2:    # Up
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xff
        elif f == 3:    # Average
            for i in range(stride):
                a = line[i - 4] if i >= 4 else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 0xff
        elif f == 4:    # Paeth
            for i in range(stride):
                a = line[i - 4] if i >= 4 else 0
                b = prev[i]
                c = prev[i - 4] if i >= 4 else 0
                pp = a + b - c
                pa, pb, pc = abs(pp - a), abs(pp - b), abs(pp - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 0xff
        out[y * stride:(y + 1) * stride] = line
        prev = line
    return w, h, bytes(out)


def main():
    src, dst, name = sys.argv[1], sys.argv[2], sys.argv[3]
    w, h, rgba = decode(src)
    with open(dst, "w") as f:
        f.write("/* generated by embed_png.py from %s */\n" % src)
        f.write("static const unsigned int k%sW = %d;\n" % (name, w))
        f.write("static const unsigned int k%sH = %d;\n" % (name, h))
        f.write("static const unsigned char k%sRGBA[] = {\n" % name)
        for i in range(0, len(rgba), 16):
            f.write("\t" + ",".join(str(b) for b in rgba[i:i + 16]) + ",\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
